Check discrepancies
cristian-data-science/airflow_master pull request #17
Opened 2024-10-17 19:06 UTC by jofigl

2024-10-18 21:56 UTC, eiurrutia commented
Comentario general:
* ¿No que finalmente dejaríamos un solo envío de mail para todos los tipos de discrepancias?
* Qué IDLE estás usando? Favor instalar flake8. Es un linting para cuidar la estructura de código y mantenerlo más ordenado y limpio

2024-10-18 22:01 UTC, eiurrutia requested changes

2024-10-21 19:55 UTC, jofigl commented on dags/config/shopify_order_data_config.py
> +    'email_on_failure': False,
quedó modificado de vuelt a true

2024-10-21 19:55 UTC, jofigl commented on dags/config/shopify_order_data_config.py
> +
línea quedó eliminada

2024-10-21 19:55 UTC, jofigl commented on dags/config/shopify_orders_line_config.py
> +    'snowflake_shopify_orders_line_table_columns': [
se eliminó el archivo que tenía la info duplicada

2024-10-21 19:56 UTC, jofigl commented on dags/erp_oms_erp_shopify_discrepancies.py
> +max_days = 7  #maximum number of days
se hizo el cambio a mayúsculas

2024-10-23 18:48 UTC, eiurrutia requested changes
<img width="695" alt="image" src="https://github.com/user-attachments/assets/8f34a101-6a72-4329-a3d7-a7d607a67777">

Respecto al resultado del chequeo en sí, en el caso de la orden 190467, si revisas el ERP, hay dos pedidos de venta asociados a esa orden de shopify:

<img width="1244" alt="image" src="https://github.com/user-attachments/assets/1b9e63bf-9da0-47b1-b641-0261162f15eb">

esto debe haber sido porque la orden inicialmente tuvo errores y el equipo de CCSS generó otra orden para facturar los productos faltantes. Sería bueno que consideremos ese caso también para que si entre ambos pedidos de venta, logro el total de artículos que vienen en la orden de shopify, no lo arrojemos como error.

2024-10-23 18:48 UTC, eiurrutia commented on dags/combined_discrepancies.py
> +MAX_DAYS = 7  # maximum number of days
Máximo número de días en qué? no queda claro qué hace esta variable

2024-10-23 18:48 UTC, eiurrutia commented on dags/combined_discrepancies.py
> +        f"AND s.PROCESSED_AT > CURRENT_TIMESTAMP - INTERVAL '{interval_days} DAYS' "
Flake8 error:  
line too long (84 > 79 characters)

2024-10-23 18:48 UTC, eiurrutia commented on dags/combined_discrepancies.py
> +        "FROM (SELECT s.ORDER_ID, s.ORDER_NAME, SUM(s.QUANTITY) AS total_cantidad_SHOPIFY "
flake8: line too long (91 > 79 characters)

2024-10-23 18:48 UTC, eiurrutia commented on dags/combined_discrepancies.py
> +        "LEFT JOIN (SELECT s.PURCHORDERFORMNUM, SUM(s.QTY) AS total_cantidad_ERP "
flake8: line too long (82 > 79 characters)

2024-10-23 18:48 UTC, eiurrutia commented on dags/combined_discrepancies.py
> +        "WHERE shop.total_cantidad_SHOPIFY != CAST(erp.total_cantidad_ERP AS INTEGER);"
flake8: line too long (87 > 79 characters)

2024-10-23 18:48 UTC, eiurrutia commented on dags/combined_discrepancies.py
> +        if not df_shopify_filtered.empty else (
flake8: trailing whitespace

2024-10-23 18:48 UTC, eiurrutia commented on dags/combined_discrepancies.py
> +         not df_oms_filtered.empty
flake8: trailing whitespace

2024-10-23 18:48 UTC, eiurrutia commented on dags/combined_discrepancies.py
> +         or not df_shopify_filtered.empty
flake8: trailing whitespace

2024-11-06 16:18 UTC, eiurrutia requested changes

2024-11-06 16:18 UTC, eiurrutia commented on dags/shopify_order_data.py
> +    # write_data_to_snowflake(
@jofigl subiste el PR con las líneas comentadas. Recuerda que si subo esto a producción, afectaré el resto de las tablas

2024-11-06 16:18 UTC, eiurrutia commented on dags/shopify_order_data.py
>  def get_shopify_orders(
@jofigl por qué estás eliminando la documentación de la función?

2024-11-06 16:18 UTC, eiurrutia commented on dags/combined_discrepancies.py
> +    'email_on_failure': False,
@jofigl esto debe estar en True a la hora de salir a producción. Favor modificar

2024-11-06 16:18 UTC, eiurrutia commented on dags/shopify_order_data.py
> +SHOPIFY_API_URL = (
@jofigl  por qué estás modificando esto?

2024-11-06 16:18 UTC, eiurrutia commented on dags/shopify_order_data.py
> -# Load environment variables from .env file
Favor no modificar estos comentarios tampoco

2024-11-06 16:18 UTC, eiurrutia commented on dags/shopify_order_data.py
> +# Configuración de los límites y tamaño de lotes
@jofigl estás segura de subir estas actualizaciones de variables?

2024-11-06 16:18 UTC, eiurrutia commented on dags/shopify_order_data.py
> +    description='DAG to extract order data from'
@jofigl modificaciones innecesarias

2024-11-06 16:18 UTC, eiurrutia commented on dags/shopify_order_data.py
> -def run_get_shopify_orders(**context):
@jofigl por qué mueves esta función?

2024-11-06 16:18 UTC, eiurrutia commented on dags/shopify_orders_line.py
@jofigl este archivo ya no debería subirse dado que su lógica se está implementando en otro dag

2024-11-07 20:26 UTC, eiurrutia requested changes

2024-11-07 20:26 UTC, eiurrutia commented on dags/shopify_order_data.py
> -        print(orders_df.head().to_string())
Dejar ambos prints por favor. Estas eliminando el de órdenes. Ahora mostremos el de orders y lines..

```
` print(orders_df.head().to_string())
        print(f'Creating/updating {len(orders_datalist)} orders from `Shopify.')`
        
        print(orders_line_df.head().to_string())
         print(f'Creating/updating {len(orders_line_df.shape[0])} orders from Shopify.')`
```

2024-11-07 20:26 UTC, eiurrutia commented on dags/shopify_order_data.py
> +
Eliminar estas líneas en blanco por favor

2024-11-07 20:26 UTC, eiurrutia commented on dags/combined_discrepancies.py
> +    'jofigonzalez@gmail.com'
Agregar mi correo y el de César por favor

2024-11-11 12:42 UTC, eiurrutia commented on dags/combined_discrepancies.py
@jofigl  Me llegó un mail con las discrepancias y recordaba que habíamos ordenado por número de orden o fecha de creación en la tabla resultante. Ahora veo que no hay ningún orden. ¿Podrías ordenar todas las tablas que se muestran en el mail por número de orden por favor?

2024-11-13 12:17 UTC, eiurrutia commented on dags/combined_discrepancies.py
@jofigl continuando con este hilo, veo lo siguiente:

1. ¿Al final cómo estas revisando si la discrepancias en las cantidades de unidades de la orden de shopify versus erp, fueron resueltas con alguna otra orden? Veo un ejemplo de una orden que reportas como error, pero que si la busco en el ERP, veo que sí tenía ya una NC asociada.

<img width="1287" alt="image" src="https://github.com/user-attachments/assets/e4f7e5b1-2940-4c80-abe0-3a0329ef2b73">

2. ¿Que rango de fecha estás definiendo para buscar discrepancias?  en el caso de la última tabla, veo órdenes del 18 de septiembre del 2021 por lo que no sé si estás buscando discrepancias onda en el "último mes". La ventana a revisar debería ser la misma que para las otras tablas que envías en el mail


3. Cuando subas los cambios, confírmame mediante la respuesta estos comentarios para saber si están resueltos please. Como por ejemplo los cambios solicitados en el comentario anterior.

Saludos!

2024-11-19 20:24 UTC, jofigl commented on dags/combined_discrepancies.py
Listo Keko! Volví a crear la tabla de shopify_orders_line que te conté en la ofi y ahora tiene fecha de creación del pedido, que necesitaba para poder poner la condición de el número de días que se quiere contar para atrás para obtener resultados. También cambié la condición para que todos los pedidos que tengan una NC asociada, no se cuenten en la tabla de resultados (antes había puesto otra condición).

2024-11-27 20:27 UTC, eiurrutia approved these changes

2024-11-27 20:27 UTC, merged